name: "Main / Pull requests build"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.txt'
      - 'LICENSE'
      - 'docs/**'
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4.1.6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # Safer alternative to Java 23; change back if needed

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: pre-commit-c-lite
        uses: pre-commit-ci/lite-action@v1.1.0

  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    needs: [pre-commit]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: mvn --no-transfer-progress verify
